// //accesing children using dom
// console.log(document.firstChild)
// console.log(document.lastChildChild)
// console.log(document.Childnodes)
// document.childNodes[0]
// document.childNodes[document.childNodes.length-1]
// console.log(document.body.firstChild)
// console.log(document.body.firstChild)
// console.log(document.body.firstChild)
// console.log(document.div.Childnodes)
// a=documnet.body.firstChild

// console.log(a.parentNode)
// console.log(a.parentElement)
// let user={
//     name:'arunsai',
//    rollno :'21-1219'


// }
// console.log(typeof user)
// console.log(user[0])
// console.log(user.rollno)
// // change dynamically like
// user.name='k.arunsai'
// console.log(user.name)
// // another form of log out
// console.log(user['name'])

// // delete the value using : delete keyword
// delete user.rollno
// console.log(user)

